FROM openjdk:17
LABEL org.opencontainers.image.authors="Anoop Sabu" \
      org.opencontainers.image.description="Generated by Anoop"
WORKDIR /app
COPY /target/*.jar ./java.jar 
CMD ["java", "-jar", "java.jar"]
